version: 2
jobs:
  test_regression_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Running tests
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/regression_model/requirements.txt
            py.test -vv packages/regression_model/tests
  

  test_ml_api:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Running tests
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            python -m pip install numpy==1.16.5
            pip install -r packages/ml_api/requirements.txt
            py.test -vv packages/ml_api/tests -p no:warnings
  

  train_and_upload_regression_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Setup env
          command: |
          
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/regression_model/requirements.txt
      - run:
          name: Publish model
          command: |
            . venv/bin/activate
          PYTHONPATH: ./packages/regression_model python3 packages/regression_model/train_pipeline.py
            python ./packages/regression_model/setup.py sdist
            curl -F package=@<file> https://kruTsJ7a3EF1xViVUULx@push.fury.io/bensnipes/
          
            

workflows:
  version: 2
  test-all:
    jobs:
      - test_regression_model
      - test_ml_api
      - train_and_upload_regression_model
      - test_ml_api:
          requires:
            - train_and_upload_regression_model