version: 2
jobs:
  test_regression_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Running tests
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/regression_model/requirements.txt
            py.test -vv packages/regression_model/tests
  

  test_ml_api:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Running tests
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip --use-feature=2020-resolver
            python -m pip install pytest --use-feature=2020-resolver
            python -m pip install flask==1.0.2 --use-feature=2020-resolver
            python -m pip install marshmallow==2.17.0 --use-feature=2020-resolver
            python -m pip install pandas==0.25.1 --use-feature=2020-resolver
            python -m pip install scikit-learn==0.21.2 --use-feature=2020-resolver
            pip install -r packages/ml_api/requirements.txt --use-feature=2020-resolver
            py.test -vv packages/ml_api/tests -p no:warnings
  

  train_and_upload_regression_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Setup env
          command: |
          
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip --use-feature=2020-resolver
            pip install -r packages/regression_model/requirements.txt --use-feature=2020-resolver
      - run:
          name: Publish model
          command: |
            . venv/bin/activate
          PYTHONPATH: ./packages/regression_model python3 packages/regression_model/train_pipeline.py
                      ./script/publish_model.sh ./packages/

            
          
            

workflows:
  version: 2
  test-all:
    jobs:
      - test_regression_model
      - test_ml_api
      - train_and_upload_regression_model
      - test_ml_api:
          requires:
            - train_and_upload_regression_model