version: 2
jobs:
  test_regression_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Running tests
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/regression_model/requirements.txt
            py.test -vv packages/regression_model/tests
  

  test_ml_api:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - py-deps-{{ checksum "packages/ml_api/requirements.txt"}}
      - run:
          name: Running tests
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip --use-feature=2020-resolver
            pip install -r packages/ml_api/requirements.txt --use-feature=2020-resolver
            py.test -vv packages/ml_api/tests -p no:warnings
      - save_cache:
          key: py-deps-{{checksum "packages/ml_api/requirements.txt"}}
          paths:
            - "/venv"
  

  train_and_upload_regression_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Setup env
          command: |
          
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip --use-feature=2020-resolver
            pip install -r packages/regression_model/requirements.txt --use-feature=2020-resolver
      - run:
          name: Train-model
          command: |
            . venv/bin/activate
            chmod +x  packages/regression_model/train_pipeline.py
      - run:
          name: Publish Model to Gemfury
          command: |
             . venv/bin/activate
             chmod +x ./script/publish_model.sh
             ./script/publish_model.sh ./packages/                         

workflows:
  version: 2
  test-all:
    jobs:
      - test_regression_model
      - test_ml_api
      - train_and_upload_regression_model
      - train_and_upload_regression_model:
          requires:
            - test_ml_api
            - test_regression_model